export const COLORS_TEST = {
  WHITE_TEST: '#FFFFFF',
  TURQUOISE_TEST: '#4DFAEF',
  TURQUOISE_PURE_TEST: '#40C8C0',
  GRAY_DISABLED: '#EFEFEF',
  BORDER_BTNRECT_MODAL: '#DCDCDC',
  BLACK_TEST: '#000000',
  GRAY_LETTER: '#030303',
};
